name: Actions Test

on:
  create: ~
  pull_request:
    types: [edited, opened, reopened, ready_for_review, review_requested, review_request_removed, closed]
  pull_request_review: ~
  pull_request_review_comment: ~
  issue_comment: ~

jobs:
  test:
    name: Test Debug
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
